### ISSUE TITLE
category limit

### ISSUE THREAD

**Issue by Jiyadgafoor** [jsbenjamins/gazecode#26]
is the category limited to 9, or can we add more categories?
@dcnieho @jsbenjamins @royhessels

**Comment by jsbenjamins** [comment]
I'm closing this issue as we will Skype/Teams about this later this week. For other users reading this issue: 

Basically, you _could_ add more categories if you are MATLAB savvy enough by changing the code in **gazecode.m** that _assigns keys to buttons on line 74 to 82_, changing the code that _generates the buttons in the right panel in line 400 to 450_, and change the code in _line 989 to 1059_ that runs the _function to process the button press 'verwerkknop'_ by adding more cases. 
However, from a study design and analysis perspective, it would be better to reconsider whether you _should_ have more than 9 AOI categories to answer your research question.
